<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgDmBlN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgDmBlN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMgDmBlN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMgDmBlN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMgDmBlN\App_KernelDevDebugContainer([
    'container.build_hash' => 'MgDmBlN',
    'container.build_id' => '9afd8e94',
    'container.build_time' => 1646056556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgDmBlN');
